- config/routes.yaml
- src/Controller/IndexController.php
- templates/base.html.twig
- templates/index/index.html.twig
Ajout du controller Index
Création de index.html.twig
Mise a jour du fichier base.html.twig
> Ajout d'un controller et d'un template index

- src/Controller/ResponsableController.php
- templates/responsable/consulter.html.twig
- Modification de la méthode consulterResponsable
- Modification de la vue responsable/consulter.html.twig et ajout du design
> modifications ResponsableController et consulter.html.twig (ajout du design)

- config/routes.yaml
- src/Controller/InstrumentController.php
- templates/instrument/consulter.html.twig
Ajout de la page consulterInstrument :
> Information de l'instrument
> Liste des accessoires
> Liste des interventions
> Liste des prêts + lien vers la page consulter eleve
Ajout des routes dans routes.yaml
> #45 gestionnaire,responsable consulter instrument

- config/routes.yaml
- src/Controller/ResponsableController.php
- templates/responsable/lister.html.twig
-Création de la méthode listerResponsable.
-Création de la vue de la méthode listerResponsable.
> Lister Responsable

- src/Controller/EleveController.php
- templates/eleve/consulter.html.twig
- Mise à jour affichage des paiements dans la vue eleve/consulter.html.twig
- Mise à jour méthode consulterEleve dans le fichier EleveController.php
> #53 eleve consulter fiche ajout paiements

- config/routes.yaml
- templates/base.html.twig
- templates/eleve/lister.html.twig
- templates/responsable/lister.html.twig
Remplacement des extends index/index.html.twig en base.html.twig dans lister eleve et lister responsable
Création des liens les responsables et les eleves dans la barre de menu
> 65 barre menu

- templates/eleve/consulter.html.twig
Creation d'un planning dans la fichee d'eleve
> ajoiut du planning dans consulter eleves avec les paiements

- config/routes.yaml
- src/Controller/CoursController.php
- templates/cours/consulter.html.twig
- Ajout de la fonction consulterCours dans le contrôleur CoursController
- création de la vue cours/consulter.html.twig affichant les informations d'un cours en fonction de son id ainsi que les élèves inscrits
> #77 tous consulter cours

- templates/classe_instrument/consulter.html.twig
- templates/cours/lister.html.twig
- templates/eleve/consulter.html.twig
- templates/eleve/lister.html.twig
- templates/instrument/consulter.html.twig
- templates/instrument/lister.html.twig
- templates/responsable/consulter.html.twig
- templates/responsable/lister.html.twig
-Ajout du titre ' Liste des Classes d'instruments ' dans consulter une classe d'instrument
-Ajout du titre ' Liste des Cours ' dans lister cours
-Ajout du titre ' Fiche de l'élève ' dans consulter un élève
-Ajout du titre ' Liste des Élèves ' dans lister les élèves
-Ajout du titre ' Fiche de l'instrument ' dans consulter un instrument
-Ajout du titre ' Liste des Instruments ' dans lister les instruments
-Ajout du titre ' Fiche du Responsable ' dans consulter un responsable
-Ajout du titre ' Liste des Responsable ' dans lister les responsables
> Ajout du titre des blocs

- config/routes.yaml
- src/Controller/ProfesseurController.php
- templates/professeur/consulter.html.twig
- templates/professeur/index.html.twig
- templates/professeur/lister.html.twig
-Création de la vue pour lister professeur.
-Rajout de la fonction listerProfesseur dans ProfesseurController.
> #87 etq tous lister professeur

- templates/professeur/consulter.html.twig
Changement d'un titre (Liste des cours de ce professeur -> Liste des cours)
Rajout du <table class="table">pour amélioration du designe
> amelioration de la table consulter professeur

- templates/professeur/consulter.html.twig
Rajout de <a href="{{ path('coursConsulter', { 'id': c.id }) }}"> dans table professeur.
> Rajout  lien dans table professeur

- composer.lock
- config/routes.yaml
- src/Controller/EleveController.php
- src/Form/EleveType.php
- templates/eleve/ajouter.html.twig
- Ajout de la fonction ajouterEleve dans le fichier EleveController.php
- Création du fichier Form/EleveType.php
- Création de la vue eleve/ajouter.html.twig et ajout du formulaire + design
> #99 gestionnaire ajouter eleve

- src/Entity/Instrument.php
Ajout d'assert pour bloquer les chaines de caractères trop petites
> Ajout assert pour bloquer de mauvaises entrées

- src/Entity/Eleve.php
Ajout des asserts dans l'entité Eleve pour les restrictions sur le formulaire d'ajout d'un élève
> ajout des asserts dans l'entité Eleve

- templates/instrument/consulter.html.twig
- Ajout du formulaire et de la méthode dans le contrôleur pour ajouter un instrument
> rectification vue instrument/consulter.html.twig

- config/routes.yaml
- src/Controller/ResponsableController.php
- src/Form/ResponsableType.php
- templates/responsable/ajouter.html.twig
- Création du fichier form\ResponsableType
- Ajout de la méthode ajouterResponsable
- Création de la vue responsable\ajouter.html.twig
- Ajout du code dans la vue et le fichier Form
- Mise à jour du fichier routes.yaml
> #100 gestionnaire ajouter responsable

- config/routes.yaml
- src/Controller/CoursController.php
- src/Controller/EleveController.php
- src/Form/CoursType.php
- templates/cours/ajouter.html.twig
Ajout de ajouterCours
Rajout de ajouterCours dans CoursController
Création de la vue de ajouterCours
Ajout de la route liée a la vue de AjouterCours
> Ajout cours

- config/routes.yaml
- src/Controller/CoursController.php
- src/Controller/ResponsableController.php
- src/Form/CoursModifierType.php
- src/Form/ResponsableModifierType.php
- templates/cours/modifier.html.twig
- templates/responsable/modifier.html.twig
Ajout CoursModifierType.php
Ajout modifier.html.twig
Ajout de la fonction modifierCours dans CoursController.php
Ajout de la route
> #121 gestionnaire modifier cours

- config/routes.yaml
- src/Controller/ResponsableController.php
- src/Form/ResponsableModifierType.php
- templates/responsable/modifier.html.twig
Ajout ResponsableModifierType.php
Ajout modifier.html.twig
Ajout de la fonction modifierResponsable dans ResponsableController.php
Ajout de la route
> Modifier Responsable

- config/routes.yaml
- src/Controller/EleveController.php
- src/Form/EleveModifierType.php
- templates/eleve/modifier.html.twig
- Création du fichier Form EleveModifierType
- Ajout de la méthode modifierEleve dans le contrôleur EleveController
- Création de la vue eleve/modifier.html.twig
- mise à jour du fichier routes.yaml
> #120 gestionnaire modifier eleve

- config/routes.yaml
- src/Controller/InstrumentController.php
- src/Form/InstrumentModifierType.php
- templates/instrument/modifier.html.twig
- Création fichier Form InstrumentModifierForm
- création vue 
- ajout méthode modifierInstrument
- MàJ fichier routes
> #119 gestionnaire modifier instrument

- templates/base.html.twig
modif du menu pour que seul l'admin voit les responsables et les eleves
> modif du menu pour que seul l'admin voit les responsables et les eleves
